import os
import psycopg2
from dotenv import load_dotenv

load_dotenv()
db_url = os.environ.get("DATABASE_URL")

try:
    conn = psycopg2.connect(db_url)
    conn.autocommit = True
    cur = conn.cursor()
    
    print("Connected to DB.")
    
    # Check if table exists
    cur.execute("""
        SELECT EXISTS (
            SELECT FROM information_schema.tables 
            WHERE table_schema = 'public' 
            AND table_name = 'detections'
        );
    """)
    exists = cur.fetchone()[0]
    
    if not exists:
        print("Table 'detections' does not exist. Creating it...")
        cur.execute("""
            CREATE TABLE detections (
                id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
                filename TEXT NOT NULL,
                original_file_url TEXT,
                processed_file_url TEXT,
                helmet_detected TEXT,
                number_plate_detected TEXT,
                plate_number TEXT
            );
        """)
        print("Table 'detections' created successfully.")
        
        # Enable RLS but allow public insert/select for now for simplicity
        # Or just leave RLS disabled (default is disabled for new tables usually unless specified)
        # But Supabase usually enables it. Let's explicitly allow access.
        
        cur.execute("ALTER TABLE detections ENABLE ROW LEVEL SECURITY;")
        
        cur.execute("""
            DO $$
            BEGIN
                IF NOT EXISTS (
                    SELECT 1 FROM pg_policies 
                    WHERE tablename = 'detections' 
                    AND policyname = 'Enable read access for all users'
                ) THEN
                    CREATE POLICY "Enable read access for all users" ON detections FOR SELECT USING (true);
                END IF;
                
                IF NOT EXISTS (
                    SELECT 1 FROM pg_policies 
                    WHERE tablename = 'detections' 
                    AND policyname = 'Enable insert access for all users'
                ) THEN
                    CREATE POLICY "Enable insert access for all users" ON detections FOR INSERT WITH CHECK (true);
                END IF;
            END
            $$;
        """)
        print("RLS policies added.")
        
    else:
        print("Table 'detections' already exists.")
        
        # Check row count
        cur.execute("SELECT COUNT(*) FROM detections;")
        count = cur.fetchone()[0]
        print(f"Current row count: {count}")

    conn.close()
    
except Exception as e:
    print(f"Error: {e}")
